import { genId } from "@/lib/id";
import { normalizeCapabilityType } from "@/lib/company/normalize";
import { formatEur } from "@/lib/status";
import { runRuleMatcher, checkCpvScope, isExclusionGrounds } from "./rule-matcher";
import { runOntologyMatcher } from "./ontology-matcher";
import { runSemanticMatcher } from "./semantic-matcher";
import { runReferenceMatcher } from "./reference-matcher";
import type { MatchingTask, MatchResult, CanonicalCompany, Passage } from "./types";
import type { PolicyItem } from "@/lib/company/types";

// ─── Constraint matcher ───────────────────────────────────────────────────────

function runConstraintMatcher(task: MatchingTask): MatchResult {
  const c = task.company_value as PolicyItem;
  const tenderText =
    typeof task.tender_value === "string"
      ? task.tender_value.toLowerCase()
      : task.tender_value === null || task.tender_value === undefined
        ? null
        : JSON.stringify(task.tender_value).toLowerCase();

  let status: "PASS" | "FAIL" | "UNCERTAIN";
  let reason: string;

  if (c.type === "WORK_TYPE" && c.operator === "EXCLUDE") {
    if (tenderText === null) {
      status = "UNCERTAIN";
      reason = `No trade scope in tender — cannot verify exclusion: ${c.value.toLowerCase().replace(/_/g, " ")}.`;
    } else {
      const excludedNorm = normalizeCapabilityType(c.value);
      const isRailSide = /rail.?side|rail.?adjacent/i.test(c.value);
      const tenderMatchesExclusion = isRailSide
        ? /rail|bahn|gleis/i.test(tenderText)
        : excludedNorm !== "OTHER"
          ? excludedNorm === normalizeCapabilityType(tenderText)
          : tenderText.includes(c.value.toLowerCase());

      if (tenderMatchesExclusion) {
        status = c.status === "CONFIRMED" ? "FAIL" : "UNCERTAIN";
        reason =
          c.status === "CONFIRMED"
            ? `Company excludes ${c.value.toLowerCase().replace(/_/g, " ")} (hard exclusion). Tender requires it.`
            : `Pending exclusion: ${c.value.toLowerCase().replace(/_/g, " ")} — requires confirmation.`;
      } else {
        status = "PASS";
        reason = `Exclusion (${c.value.toLowerCase().replace(/_/g, " ")}) not triggered by tender trade scope.`;
      }
    }
  } else if ((c.type === "COUNTRY" || c.type === "REGION") && c.operator === "OUTSIDE") {
    if (tenderText === null) {
      status = "UNCERTAIN";
      reason = `No place of performance in tender — cannot verify country/region exclusion.`;
    } else {
      const excluded = c.value.toLowerCase();
      if (tenderText.includes(excluded)) {
        status = c.status === "CONFIRMED" ? "FAIL" : "UNCERTAIN";
        reason =
          c.status === "CONFIRMED"
            ? `Company excludes work outside ${c.value}. Tender location appears to be outside it.`
            : `Pending country/region constraint for ${c.value}.`;
      } else {
        status = "PASS";
        reason = `Country/region constraint (outside ${c.value}) not triggered.`;
      }
    }
  } else if (c.type === "MAX_PROJECT_VALUE" && c.operator === "MAX") {
    const tenderValue = typeof task.tender_value === "number" ? task.tender_value : null;
    const limit = parseFloat(c.value);
    if (tenderValue === null) {
      status = "UNCERTAIN";
      reason = "No contract value in tender — cannot verify max project constraint.";
    } else if (!isNaN(limit) && tenderValue > limit) {
      status = c.status === "CONFIRMED" ? "FAIL" : "UNCERTAIN";
      reason = `Tender value ${formatEur(tenderValue)} exceeds company hard limit ${formatEur(limit)}.`;
    } else {
      status = "PASS";
      reason = `Tender value within company max project constraint.`;
    }
  } else if ((c.type === "JV" || c.type === "CONSORTIUM") && c.operator === "EXCLUDE") {
    // JV hard exclusion is handled by partner-threshold in rule-matcher; here just flag it
    status = "PASS";
    reason = "No partner/JV required for this contract size.";
  } else {
    status = "UNCERTAIN";
    reason = `Constraint type ${c.type}/${c.operator} not evaluated deterministically.`;
  }

  return {
    id: genId("RES"),
    task_id: task.id,
    requirement_id: task.requirement_id,
    label: task.label,
    status,
    severity: task.severity,
    method: "CONSTRAINT",
    layer: "HARD_GATE",
    reason,
    tender_evidence: task.tender_evidence,
    company_evidence: [c.id],
    company_fact: `${c.type} ${c.operator} ${c.value}`,
    aspect: task.aspect,
  };
}

// ─── Main dispatcher ──────────────────────────────────────────────────────────

export async function routeAndRun(
  task: MatchingTask,
  company: CanonicalCompany,
  passages: Passage[] = [],
): Promise<MatchResult> {
  // Standalone constraint tasks (generated by generateConstraintTasks)
  if (task.matcher_type === "CONSTRAINT") {
    return runConstraintMatcher(task);
  }

  // trade_scope: run ontology matcher AND check work-type exclusions
  if (task.requirement_id === "trade_scope") {
    const raw =
      typeof task.tender_value === "string"
        ? task.tender_value
        : Array.isArray(task.tender_value)
          ? task.tender_value.join(" ")
          : "";
    const constraints = (company.constraints ?? []).filter(
      (r) =>
        r.status !== "REJECTED" &&
        r.severity === "HARD" &&
        r.operator === "EXCLUDE" &&
        r.type === "WORK_TYPE",
    );
    const hit = constraints.find((r) => {
      if (/lead|main contractor|generalunternehmer/i.test(r.value))
        return raw.toLowerCase().includes(r.value.toLowerCase());
      if (/rail.?side|rail.?adjacent/i.test(r.value))
        return /rail|bahn|gleis/i.test(raw);
      const concept = normalizeCapabilityType(r.value);
      return concept !== "OTHER"
        ? concept === normalizeCapabilityType(raw)
        : raw.toLowerCase().includes(r.value.toLowerCase());
    });
    if (hit)
      return {
        id: genId("RES"),
        task_id: task.id,
        requirement_id: task.requirement_id,
        label: task.label,
        status: hit.status === "CONFIRMED" ? "FAIL" : "UNCERTAIN",
        severity: task.severity,
        method: "CONSTRAINT",
        layer: "HARD_GATE",
        reason: `${hit.status === "CONFIRMED" ? "Confirmed" : "Pending review"} hard exclusion: ${hit.value}.`,
        tender_evidence: task.tender_evidence,
        company_evidence: [hit.id],
        aspect: task.aspect,
      };
  }

  // trade_scope: a CPV code against the company's CPV prefixes is deterministic and beats the
  // label ontology, which cannot read a code.
  if (task.requirement_id === "trade_scope" && typeof task.tender_value === "string" && /^\d{8}/.test(task.tender_value)) {
    const cpv = checkCpvScope(task, company);
    if (cpv) return cpv;
  }
  // eligibility_proofs: the eForms exclusion-ground codes (§§ 123/124 GWB) are a standard
  // self-declaration every bidder files, not a qualification to hold.
  if (task.requirement_id === "eligibility_proofs" && isExclusionGrounds(task.tender_value)) {
    return {
      id: genId("RES"), task_id: task.id, requirement_id: task.requirement_id, label: task.label,
      status: "PASS", severity: "SOFT", method: "DETERMINISTIC", layer: "HARD_GATE",
      reason: "Only the standard §§ 123/124 GWB exclusion grounds are listed; covered by the bidder's self-declaration (Eigenerklärung, Formblatt 124), no special proof.",
      tender_evidence: task.tender_evidence, company_evidence: [], company_fact: "Self-declaration with the bid", aspect: task.aspect,
    };
  }

  switch (task.matcher_type) {
    case "RULE":
      return runRuleMatcher(task, company);
    case "ONTOLOGY":
      return runOntologyMatcher(task, company);
    case "SEMANTIC":
      return runSemanticMatcher(task, company, passages);
    case "REFERENCE":
      return runReferenceMatcher(task, company);
    default:
      return runRuleMatcher(task, company);
  }
}
