/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

// Convenience re-exports for the matching engine
export type Lot = import("./api-types").components["schemas"]["Lot"];

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Contract
         * @description Never called by the web app. Exists so every shared model appears in
         *     /openapi.json before the routers that use them are written.
         */
        get: operations["contract_contract_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CompanyCreate */
        CompanyCreate: {
            /** Text */
            text: string;
        };
        /** CompanyProfile */
        CompanyProfile: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Home Base */
            home_base: string;
            home_base_geo?: components["schemas"]["GeoPoint"] | null;
            /** Regions */
            regions?: string[];
            /** Radius Km */
            radius_km?: number | null;
            /** Trades */
            trades?: string[];
            /** Cpv Prefixes */
            cpv_prefixes?: string[];
            /** Contract Min Eur */
            contract_min_eur?: number | null;
            /** Contract Max Eur */
            contract_max_eur?: number | null;
            /** Partner Threshold Eur */
            partner_threshold_eur?: number | null;
            /** References Held */
            references_held?: string[];
            /** Hard Exclusions */
            hard_exclusions?: string[];
            /** Guarantee Capacity Eur */
            guarantee_capacity_eur?: number | null;
            /** Self Perform Share Pct */
            self_perform_share_pct?: number | null;
            /** Earliest Start */
            earliest_start?: string | null;
            /**
             * Capacity Per Week
             */
            capacity_per_week: number | null;
            /**
             * Raw Text
             * @default
             */
            raw_text: string;
        };
        /**
         * Confidence
         * @enum {string}
         */
        Confidence: "high" | "medium" | "low" | "not_found";
        /**
         * ContractBundle
         * @description Aggregates every shared model so OpenAPI emits them all (see main.contract).
         */
        ContractBundle: {
            tender: components["schemas"]["TenderDetail"];
            tender_summary: components["schemas"]["TenderSummary"];
            company: components["schemas"]["CompanyProfile"];
            company_create: components["schemas"]["CompanyCreate"];
            verdict: components["schemas"]["Verdict"];
            screen_request: components["schemas"]["ScreenRequest"];
            ingest_request: components["schemas"]["IngestRequest"];
            ingest_job: components["schemas"]["IngestJob"];
        };
        /** CriterionResult */
        CriterionResult: {
            /** Criterion */
            criterion: string;
            status: components["schemas"]["Status"];
            kind: components["schemas"]["RuleKind"];
            /** Reason En */
            reason_en: string;
            /** Tender Evidence */
            tender_evidence?: components["schemas"]["Evidence"][];
            /** Tender Value */
            tender_value?: unknown | null;
            /** Company Fact */
            company_fact?: string | null;
        };
        /**
         * Evidence
         * @description Where a fact was read: document name, page, verbatim German quote.
         */
        Evidence: {
            /** Doc */
            doc: string;
            /** Page */
            page?: number | null;
            /** Quote De */
            quote_de: string;
        };
        /**
         * Fact
         * @description One extracted field: value plus how sure we are and where it came from.
         *
         *     `value` is typed loosely on purpose; the 15 fields carry different shapes and
         *     the rule engine casts per criterion. `not_found` means the documents were read
         *     and the fact was absent, never that we guessed.
         */
        Fact: {
            /** Value */
            value?: unknown | null;
            /** @default not_found */
            confidence: components["schemas"]["Confidence"];
            /** Evidence */
            evidence?: components["schemas"]["Evidence"][];
        };
        /** GeoPoint */
        GeoPoint: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Label */
            label?: string | null;
        };
        /** IngestJob */
        IngestJob: {
            /** Id */
            id: string;
            /** @default queued */
            stage: components["schemas"]["JobStage"];
            /**
             * Pct
             * @default 0
             */
            pct: number;
            /** Message */
            message?: string | null;
            /** Tender Id */
            tender_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** IngestRequest */
        IngestRequest: {
            /** Notice Url */
            notice_url?: string | null;
            /** Title */
            title?: string | null;
            /** Buyer Name */
            buyer_name?: string | null;
        };
        /**
         * JobStage
         * @enum {string}
         */
        JobStage: "queued" | "downloading" | "extracting_text" | "extracting_facts" | "done" | "error";
        /** Lot */
        Lot: {
            /** Id */
            id: string;
            /** Title */
            title?: string | null;
            /** Cpv */
            cpv?: string | null;
            /** Value Eur */
            value_eur?: number | null;
            /** Trade */
            trade?: string | null;
        };
        /**
         * Overall
         * @enum {string}
         */
        Overall: "Bid" | "Consider" | "NoGo";
        /**
         * RuleKind
         * @enum {string}
         */
        RuleKind: "numeric" | "semantic";
        /** ScreenRequest */
        ScreenRequest: {
            /** Company Id */
            company_id: string;
            /** Tender Ids */
            tender_ids?: string[] | null;
        };
        /**
         * Status
         * @description Outcome of one criterion for one company × tender.
         * @enum {string}
         */
        Status: "Blocker" | "Risk" | "OK" | "Unknown";
        /**
         * TenderDetail
         * @description Summary plus the notice metadata the pipeline already parsed, the lots,
         *     the documents we hold, and the fact sheet once extraction has run.
         */
        TenderDetail: {
            /** Id */
            id: string;
            /** Title */
            title?: string | null;
            /** Buyer Name */
            buyer_name?: string | null;
            /** Place City */
            place_city?: string | null;
            /** Place Nuts */
            place_nuts?: string | null;
            /** Cpv Main */
            cpv_main?: string | null;
            /** Estimated Value Eur */
            estimated_value_eur?: number | null;
            /** Submission Deadline */
            submission_deadline?: string | null;
            /** Published */
            published?: string | null;
            /** Notice Url */
            notice_url?: string | null;
            /**
             * Lot Count
             * @default 1
             */
            lot_count: number;
            /**
             * Docs Retrieved
             * @default false
             */
            docs_retrieved: boolean;
            /**
             * Source
             * @default oeffentlichevergabe.de
             */
            source: string;
            /** Description */
            description?: string | null;
            /** Lots */
            lots?: components["schemas"]["Lot"][];
            /** Notice */
            notice?: {
                [key: string]: unknown;
            };
            /** Documents */
            documents?: components["schemas"]["TenderDocument"][];
            fact_sheet?: components["schemas"]["TenderFactSheet"] | null;
        };
        /** TenderDocument */
        TenderDocument: {
            /** Name */
            name: string;
            /** Url */
            url?: string | null;
            /** Local Path */
            local_path?: string | null;
            /** Pages */
            pages?: number | null;
            /**
             * Text Extracted
             * @default false
             */
            text_extracted: boolean;
        };
        /**
         * TenderFactSheet
         * @description The 15 fields an estimator screens on. See docs/design.md for shapes.
         */
        TenderFactSheet: {
            trade_scope?: components["schemas"]["Fact"];
            place_of_performance?: components["schemas"]["Fact"];
            estimated_value?: components["schemas"]["Fact"];
            lots?: components["schemas"]["Fact"];
            references_required?: components["schemas"]["Fact"];
            eligibility_proofs?: components["schemas"]["Fact"];
            construction_window?: components["schemas"]["Fact"];
            guarantees?: components["schemas"]["Fact"];
            penalty?: components["schemas"]["Fact"];
            self_performance_min_pct?: components["schemas"]["Fact"];
            side_offers_allowed?: components["schemas"]["Fact"];
            consortium_allowed?: components["schemas"]["Fact"];
            submission_deadline?: components["schemas"]["Fact"];
            special_qualifications?: components["schemas"]["Fact"];
            contractor_role?: components["schemas"]["Fact"];
        };
        /**
         * TenderSummary
         * @description One row in the weekly triage view. One record per notice; lots nested.
         */
        TenderSummary: {
            /** Id */
            id: string;
            /** Title */
            title?: string | null;
            /** Buyer Name */
            buyer_name?: string | null;
            /** Place City */
            place_city?: string | null;
            /** Place Nuts */
            place_nuts?: string | null;
            /** Cpv Main */
            cpv_main?: string | null;
            /** Estimated Value Eur */
            estimated_value_eur?: number | null;
            /** Submission Deadline */
            submission_deadline?: string | null;
            /** Published */
            published?: string | null;
            /** Notice Url */
            notice_url?: string | null;
            /**
             * Lot Count
             * @default 1
             */
            lot_count: number;
            /**
             * Docs Retrieved
             * @default false
             */
            docs_retrieved: boolean;
            /**
             * Source
             * @default oeffentlichevergabe.de
             */
            source: string;
        };
        /** Verdict */
        Verdict: {
            /** Tender Id */
            tender_id: string;
            /** Company Id */
            company_id: string;
            overall: components["schemas"]["Overall"];
            /** Criteria */
            criteria: components["schemas"]["CriterionResult"][];
            /** Summary En */
            summary_en?: string | null;
            /**
             * Blockers
             * @default 0
             */
            blockers: number;
            /**
             * Risks
             * @default 0
             */
            risks: number;
            /**
             * Unknowns
             * @default 0
             */
            unknowns: number;
            /** Rank */
            rank?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    contract_contract_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractBundle"];
                };
            };
        };
    };
}
